allow --bip and --fixed-cidr together
if using --fixed-cidr and you want a fixed --bip,
you can not specify --bridge due to docker making
those options mutually exclusive.

for example, this hiera data:
docker::fixed_cidr: '172.16.16.0/22'
docker::bip:        '172.16.16.1/22'

will fail with:
Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Evaluation Error: Error while evaluating a Function Call, You
must provide the $bridge parameter.

specifying docker::bridge results in:
FATA[0000] Error starting daemon: You specified -b & --bip, mutually
exclusive options. Please specify only one.