Fix docker_worker_join_token evaluation
When this fact was evaluated, an exception was raised:
Error: Facter: Error while resolving custom fact fact='docker_worker_join_token', resolution='<anonymous>': private method `execute' called for Facter::Util::Resolution:Class

Switch from Facter::Util::Resolution to Facter::Core::Execution and set
a time limit of 90s to match the rest of the file.